refactoring code; add special formatter
kompendium-ano/factom-did-rust pull request #2
Opened 2021-07-21 19:04 UTC by ivanuzk

WIP

- code polishing
- refactoring to make code compact and concise
- adds special formatting rules

2021-07-23 06:17 UTC, sigrlami requested changes
Overall good, need small tweaks

2021-07-23 06:17 UTC, sigrlami commented on rustfmt.toml
> +wrap_comments = true
I think that's strange, it messes up Emacs setup, can you hide temporary?

2021-07-23 06:17 UTC, sigrlami commented on src/client/did.rs
> +return "<{}.{} (management_keys={}, did_keys={}, services={})>".format(self.module, type_(self).__name__, self.management_keys.len(), self.did_keys.len(), self.services.len());
I would prefer ditching self at all and refer to internal representation, look if that possible

2021-09-15 11:33 UTC, ivanuzk commented
LGTM

2021-09-15 11:34 UTC, merged